### ISSUE TITLE
Sending message fails with error SSL3_GET_RECORD:decryption failed 

### ISSUE THREAD

**Issue by genieplus** [Azure/azure-service-bus-samples#3]
I am testing the send.c example with my local service bus 1.1 installation.
The sending process fails with the error message:
```
CALL pn_messenger_settle... RETURNED 0
CALL pn_messenger_stop... RETURNED 0
CALL pn_messenger_put... RETURNED 0
CALL pn_messenger_send... process_input_ssl[890] -> reason: 1
[0x1c97110]:ERROR amqp:connection:framing-error SSL Failure: error:1408F119:SSL routines:SSL3_GET_RECORD:decryption failed or bad record mac
RETURNED 0
Sent TextMessage with id
19b4cacc-e52f-4080-8e8ccf1fe0683001
Message status PN_STATUS_ABORTED
```

Before getting this error message, the program was able to send many messages (1284,  1564, 4000 ...).

Any idea?

**Comment by JamesBirdsall** [comment]
I haven't seen that before. An SSL framing error suggests that something is going wrong at the network level. If one end or the other were configuring SSL incorrectly, that would normally show up as a negotiation failure, or a complete inability to exchange data. A working connection dying in the middle like that -- maybe the TCP connection was killed? I don't really know.
